#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

export VER=$(npm pkg get version | xargs echo)

echo "FIX LINTER"
yarn lint:fix
echo "FIX LINTER: [OK]"

echo "Update index.html version"
echo " > Current Version: $VER"
sed -i -E "s/Version [0-9\.]+[0-9]/Version ${VER}/g" public/index.html
git add public/index.html
echo "Update index.html version: [OK]"

echo "TEST"
yarn pretest
yarn test
yarn posttest
echo "TEST: [OK]"

echo "Build"
yarn build
echo "Build: [OK]"
